### ISSUE TITLE
trial of refusal

### ISSUE THREAD

**Issue by bczretribution** [AaronGullickson/mekhq#64] opened 2024-04-14 18:01 UTC
### Environment
storyarcs 0.3

### Description
having taken a warder stance, Mathius challenges me to a trial of refusal.  dialog clearly states only 2 mechs are allowed.  Scenario spawns with Mathius as the opfor, but with my entire TO&E deployed. (including Mathius)

### Files
![image](https://github.com/AaronGullickson/mekhq/assets/34722287/7b0cee9d-355a-4161-bce1-dd456bccf574)

**Comment by AaronGullickson** [comment] 2024-04-14 19:54
Yes, this is a duplicate of #55 which has already been fixed for the next release. In the meantime, the workaround is to go to undeploy everything from the TO&E screen, which will then give you the currect deployment limitations.

**Closed by AaronGullickson** 2024-04-14 19:54 UTC
